"""Updated user table-caretaker id is nullable

Revision ID: 60606489902a
Revises: 8b912693f9ab
Create Date: 2024-07-19 09:48:06.161982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60606489902a'
down_revision = '8b912693f9ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserPatient', schema=None) as batch_op:
        batch_op.alter_column('caretaker_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserPatient', schema=None) as batch_op:
        batch_op.alter_column('caretaker_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
