"""Initial migration

Revision ID: 8b912693f9ab
Revises: 
Create Date: 2024-07-19 09:38:09.704622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b912693f9ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Caretaker',
    sa.Column('caretaker_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('mobile', sa.String(length=80), nullable=True),
    sa.Column('caretaker_pic', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('caretaker_id'),
    sa.UniqueConstraint('caretaker_pic'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('name')
    )
    op.create_table('UserPatient',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('dob', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('caretaker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caretaker_id'], ['Caretaker.caretaker_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Acquaintances',
    sa.Column('acquaintances_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('acquaintances_pic', sa.String(length=80), nullable=True),
    sa.Column('relation', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['UserPatient.user_id'], ),
    sa.PrimaryKeyConstraint('acquaintances_id'),
    sa.UniqueConstraint('acquaintances_pic')
    )
    op.create_table('Tasks',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('emoji', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UserPatient.user_id'], ),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('emoji'),
    sa.UniqueConstraint('time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tasks')
    op.drop_table('Acquaintances')
    op.drop_table('UserPatient')
    op.drop_table('Caretaker')
    # ### end Alembic commands ###
